; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]

[env:uno_scanner]
platform = atmelavr
board = uno
framework = arduino
src_dir = src/scanner_I2C
monitor_speed = 115200

build_flags =
    -D I2C_SCANNER

[env:uno_bme280]
platform = atmelavr
board = uno
framework = arduino
src_dir = src/bme280
monitor_speed = 115200
lib_deps = adafruit/Adafruit BME280 Library@^2.3.0
upload_port = /dev/cu.usbserial-14320


build_flags =
    -D BME280